env:
  browser: true
  es2021: true
  node: true
extends:
  - 'plugin:vue/essential'
  - '@vue/airbnb'
  - '@vue/typescript'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  route: readonly
  moment: writable
parserOptions:
  ecmaVersion: 12
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - vue
  - '@typescript-eslint'
settings: {
  'import/resolver': 'webpack'
}
rules: {
  'import/no-extraneous-dependencies': 'off',
  'no-console': 'off',
  'max-len': 'off',
  'camelcase': 'off',
  'class-methods-use-this': 'off',
  'prefer-destructuring': 'off',
  'semi': ['error', 'never']
}
