version: '3'

services:
  php:
    container_name: "php-fpm"
    restart: always
    build:
      context: ./docker/php
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
    volumes:
      - .:/var/www
    networks: 
      - backend

  nginx:
    image: nginx:1.19-alpine
    container_name: "nginx"
    restart: always
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
      - ./storage/logs:/var/log
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    networks: 
      - backend
    depends_on:
      - php
      - certbot
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    container_name: "certbot"
    image: certbot/certbot
    volumes:
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  postgres:
    container_name: "postgres"
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_DB: launcher
      POSTGRES_USER: launcher
      POSTGRES_PASSWORD: secret
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks: 
      - backend
    ports:
      - "5432:5432"

      
  
networks: 
  backend:
          
volumes:
  database-data: