version: '3'
services:
    ezgames:
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        image: emodyz/ezgames
        restart: always
        ports:
            - '80:80'
            - "443:443"
        environment:
            NGINX_HOST: '${EZG_NGINX_HOST}'
            NGINX_ENVSUBST_TEMPLATE_SUFFIX: '${EZG_NGINX_SHOULD_PUBLISH_TEMPLATES}'
        volumes:
            - '.:/var/www/app'
            - 'ezgames_tls:/etc/letsencrypt'
            - 'ezgames_nginx:/etc/nginx/conf.d'
        networks:
            - ezgames
        depends_on:
            - php
            - pgsql
            - redis
            # - meilisearch
            # - smtp
    php:
        image: emodyz/ezgames-php:v0.0.2
        restart: always
        ports:
            - '9000:9000'
            - '6001:6001'
        volumes:
            - '.:/var/www/app'
            - 'ezgames_tls:/etc/letsencrypt'
        networks:
            - ezgames
        extra_hosts:
            - "host.docker.internal:host-gateway"
    pgsql:
        image: postgres:13-alpine
        restart: always
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'ezgames_pgsql:/var/lib/postgresql/data'
        networks:
            - ezgames
        healthcheck:
          test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
    redis:
        image: redis:6-alpine
        restart: always
        ports:
            - '6379:6379'
        volumes:
            - 'ezgames_redis:/data'
        networks:
            - ezgames
        healthcheck:
          test: ["CMD", "redis-cli", "ping"]
    #meilisearch:
    # TODO: Generate a masterKey for meilisearch : export MEILI_MASTER_KEY=xxx
    #    image: getmeili/meilisearch:latest
    #    restart: always
    #    ports:
    #        - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
    #    volumes:
    #        - 'ezgames_meilisearch:/data.ms'
    #    networks:
    #        - ezgames
    #smtp:
    #    image: boky/postfix:latest
    #    restart: always
    #    ports:
    #        - "587:587"
    #    environment:
    #        ALLOW_EMPTY_SENDER_DOMAINS: "yes"
    #    networks:
    #        - ezgames

networks:
    ezgames:
        # TODO: is this networking mode suitable for production ??
        driver: bridge
volumes:
    # TODO: Find a way to save .env in a volume since we cant map a volume to a single file
    ezgames_nginx:
        driver: local
    ezgames_tls:
        driver: local
    ezgames_pgsql:
        driver: local
    ezgames_redis:
        driver: local
    ezgames_meilisearch:
        driver: local
