# TODO: Generate a masterKey for meilisearch : export MEILI_MASTER_KEY=xxx
version: '3'
services:
    ezgames:
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        image: emodyz/ezgames
        ports:
            - '80:80'
            - "443:443"
        volumes:
            - '.:/var/www/app'
            - './docker/app/index.php:/var/www/test/index.php'
        networks:
            - ezgames
        depends_on:
            - php
            - pgsql
            - redis
            - meilisearch
    php:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        image: emodyz/ezgames-php
        ports:
            - '9000:9000'
        volumes:
            - '.:/var/www/app'
            - './docker/app/index.php:/var/www/test/index.php'
        networks:
            - ezgames
    pgsql:
        image: postgres:13-alpine
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'ezgamespgsql:/var/lib/postgresql/data'
        networks:
            - ezgames
        healthcheck:
          test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
    redis:
        image: redis:alpine
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'ezgamesredis:/data'
        networks:
            - ezgames
        healthcheck:
          test: ["CMD", "redis-cli", "ping"]
    meilisearch:
        image: getmeili/meilisearch:latest
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        volumes:
            - 'ezgamesmeilisearch:/data.ms'
        networks:
            - ezgames
networks:
    ezgames:
        driver: bridge
volumes:
    ezgamespgsql:
        driver: local
    ezgamesredis:
        driver: local
    ezgamesmeilisearch:
        driver: local
