version: '3'

services:
  php:
    container_name: "php-fpm"
    restart: always
    build:
      context: ./docker/php
    environment:
      - APP_ENV=${APP_ENV}
    volumes:
      - .:/var/www/html
    networks: 
      - backend

  nginx:
    image: nginx:1.19
    container_name: "nginx"
    restart: always
    volumes:
      - .:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
      #- ./storage/logs:/var/log
    networks: 
      - backend
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"

  redis:
    container_name: "redis"
    image: "redis:alpine"
    restart: always
    networks: 
      - backend
    ports:
      - "6379:6379"

  postgres:
    container_name: "postgres"
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_DB: launcher
      POSTGRES_USER: launcher
      POSTGRES_PASSWORD: secret
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks: 
      - backend
    ports:
      - "5432:5432"
  
networks: 
  backend:
          
volumes:
  database-data: