version: '3'

services:
  php:
    container_name: "php-fpm"
    restart: always
    build:
      context: ./docker/php
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
    volumes:
      - .:/var/www
    networks: 
      - backend

  nginx:
    container_name: "nginx"
    restart: always
    build:
      context: ./docker/nginx
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./storage/logs:/var/log
    networks: 
      - backend
    depends_on:
      - php
    ports:
      - "80:80"

  postgres:
    container_name: "postgres"
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_DB: launcher
      POSTGRES_USER: launcher
      POSTGRES_PASSWORD: secret
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks: 
      - backend
    ports:
      - "5432:5432"

      
  
networks: 
  backend:
          
volumes:
  database-data: