<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bridge.proto

namespace Bridge;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bridge.CheckForCpUpdateReply</code>
 */
class CheckForCpUpdateReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string target = 1;</code>
     */
    protected $target = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $target
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Bridge::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string target = 1;</code>
     * @return string
     */
    public function getTarget()
    {
        return $this->target;
    }

    /**
     * Generated from protobuf field <code>string target = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTarget($var)
    {
        GPBUtil::checkString($var, True);
        $this->target = $var;

        return $this;
    }

}

